### ISSUE TITLE
GlycanFormatConverter API address update

### ISSUE THREAD

**Issue by yamadaissaku** [akulmehta/GlycoGlyphPublic#15]
The glycanformatconverter API has been updated. Check the API URL (https://api.glycosmos.org/glycanformatconverter/#2.5.2-glycoct-to-wurcs-get).

You can change it to the API address.

Line 246 of https://github.com/akulmehta/GlycoGlyphPublic/blob/Development/src/modules/getGTCID.js

* let url = "https://api.glycosmos.org/glycanformatconverter/2.3.2-snapshot/glycoct2wurcs/"
* let url = "https://api.glycosmos.org/glycanformatconverter/2.5.2/glycoct2wurcs/"

**Comment by akulmehta** [comment]
Thanks @yamadaissaku will add it to the next release.

**Comment by akulmehta** [comment]
Fixed in v2.1.2
