### ISSUE TITLE
Image sources in index.html in public

### ISSUE THREAD

**Issue by leptoceratops** [akulmehta/GlycoGlyphPublic#30]
In index.html, the <img> tag's "src" are paths with an extra / , i.e. `<img src="/assets/images/copy.svg" alt="copy" width="20px">` should be `<img src="assets/images/copy.svg" alt="copy" width="20px">`. Is this right?

**Comment by akulmehta** [comment]
It depends on where the application is deployed. This is not an issue. Please send me emails for questions rather than raising issues.

**Comment by leptoceratops** [comment]
Sure. Thank you. Which e-mail shall I use?

**Comment by akulmehta** [comment]
The one provided in the paper https://doi.org/10.1093/bioinformatics/btaa190

**Comment by akulmehta** [comment]
I have pushed some code in the Development branch which might help with this and updated the README there. Please check and check your email for more detailed instructions.

**Comment by leptoceratops** [comment]
Thank you!
