### ISSUE TITLE
Copy functionality not working properly in chrome.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [akulmehta/GlycoGlyphPublic#35]
**Describe the bug**
Copy functionality of GlycoCT sequence does not propelry in all browsers, specifically chrome.

/GlycoGlyphPublic/src/modules/copyTextFromElement.js
/GlycoGlyphPublic/public/js/glycoglyph.js

copyText() function should return promise object and copyTextFromElement should wait on the object. I have added modified code below,

//If you want to copyText from Element
  function copyTextFromElement(elementID) {
    let element = document.getElementById(elementID); //select the element

    let elementText = element.innerText; //get the text content from the element

    if (element.tagName == 'INPUT' ) {
      elementText = element.value;
    }

    elementText = elementText.trim();

    if (elementText != '') {
      //use the copyText function below
      copyText(elementText).then(() => {
        alert('Copied: \n' + elementText);
      })
      .catch(() => {
        alert('Could not copy text.');
      });
    }else {
      alert('Nothing to copy.');
    }
  }

  //If you only want to put some Text in the Clipboard just use this function
  // and pass the string to copied as the argument.
  function copyText(text) {
    return navigator.clipboard.writeText(text);
  }

**Comment by akulmehta** [comment]
Hi @sujeetvkulkarni. I cannot reproduce the error in chrome. 

Example: https://glycotoolkit.com/Tools/GlycoGlyph/

![image](https://user-images.githubusercontent.com/42812604/162255796-5d064ce7-c170-4339-b08c-0f59dc893f3a.png)

**Comment by sujeetvkulkarni** [comment]
Hi @akulmehta copy pop-up comes but if you try to paste the copied GlycoCT string on text editor it was not working.

**Comment by akulmehta** [comment]
Sorry - can't reproduce yet. It copies it fine for me. I wonder if this is OS related - I am on Windows 10.

**Comment by sujeetvkulkarni** [comment]
Maybe I am on macOS Monterey Version 12.1 and Chrome Version 100.0.4896.75
(Official Build) (x86_64).

**Comment by akulmehta** [comment]
Does the code you proposed fix this for you?

**Comment by sujeetvkulkarni** [comment]
Yes, navigator.clipboard.writeText(text); function returns a promise object
and we should handle it with then construct before proceeding. That's what
the proposed code does.
